CREATE TABLE IF NOT EXISTS user_registry (
 user_id TEXT PRIMARY KEY,
 email TEXT NOT NULL DEFAULT '',
 name TEXT NOT NULL DEFAULT '',
 first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)