CREATE TABLE IF NOT EXISTS user_feedback (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 email TEXT NOT NULL DEFAULT '',
 message TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)