import { db, admin } from "hatchable";
export const access="public";
export const methods=["GET","POST","PUT","DELETE"];
export default async function(req,res){
 if(req.method==="GET"){if(req.query&&req.query.summary==="1"){const params=[];let where="";if(req.query.lesson){params.push(req.query.lesson);where=" WHERE lesson=$"+params.length}const home=req.query.home==="1";const sql=home?"SELECT lesson,MIN(topic) AS topic,question_group,COUNT(*)::int AS count,MIN(created_at) AS first_created,MAX(created_at) AS last_created FROM questions"+where+" GROUP BY lesson,question_group ORDER BY MIN(created_at) ASC":"SELECT lesson,MIN(topic) AS topic,question_group,COUNT(*)::int AS count,ARRAY_AGG(id ORDER BY created_at ASC) AS question_ids,MIN(created_at) AS first_created,MAX(created_at) AS last_created FROM questions"+where+" GROUP BY lesson,question_group ORDER BY MIN(created_at) ASC";const {rows}=await db.query(sql,params);return res.json({summary:true,groups:rows})}const params=[];let where="";if(req.query&&req.query.lesson){params.push(req.query.lesson);where=" WHERE lesson=$1"}if(req.query&&req.query.topic){params.push(req.query.topic);where+=(where?" AND ":" WHERE ")+"(question_group=$"+params.length+" OR topic=$"+params.length+")"}const {rows}=await db.query("SELECT id,lesson,topic,question_group,question,option_a,option_b,option_c,option_d,option_e,correct,difficulty,explanation,created_at FROM questions"+where+" ORDER BY created_at ASC",params);return res.json(rows.map(q=>({...q,options:[q.option_a,q.option_b,q.option_c,q.option_d,q.option_e]})))}
 const b=req.body||{};
 if(req.method==="POST"||req.method==="PUT"||req.method==="DELETE"){
  const allowed=await admin.require(req,res); if(!allowed)return;
 }
 if(req.method==="DELETE"){if(!b.id)return res.status(400).json({error:"ID gerekli"});await db.query("DELETE FROM questions WHERE id=$1",[b.id]);return res.json({ok:true});}
 if(req.method==="PUT"){if(!b.id||!b.lesson||!b.question||!Array.isArray(b.options)||b.options.length!==5||!b.correct)return res.status(400).json({error:"Eksik alan"});await db.query("UPDATE questions SET lesson=$1,topic=$2,question_group=$3,question=$4,option_a=$5,option_b=$6,option_c=$7,option_d=$8,option_e=$9,correct=$10,difficulty=$11,explanation=$12 WHERE id=$13",[b.lesson,b.topic||"",b.question_group||"",b.question,...b.options,b.correct,b.difficulty||"Orta",b.explanation||"",b.id]);return res.json({ok:true});}
 if(!b.lesson||!b.question||!Array.isArray(b.options)||b.options.length!==5||!b.correct)return res.status(400).json({error:"Eksik alan"}); const {rows}=await db.query("INSERT INTO questions (lesson,topic,question_group,question,option_a,option_b,option_c,option_d,option_e,correct,difficulty,explanation) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id",[b.lesson,b.topic||"",b.question_group||"",b.question,...b.options,b.correct,b.difficulty||"Orta",b.explanation||""]); return res.status(201).json(rows[0]);
}